name: shamir
favicon: null
layout_spectrum: 0.05455351248383522
typography_spectrum: 0.7671999384183437
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5707020305562764
  lightness: 0.8233475142624229
  saturation: 0.86433438770473
  rhythmicContrast: 0.17045508790761232
purpose: []
